# Generated by Django 4.2.4 on 2023-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User1", models.CharField(max_length=200)),
                ("User2", models.CharField(max_length=200)),
                ("User3", models.CharField(max_length=200)),
                ("User4", models.CharField(max_length=200)),
                ("point1", models.IntegerField()),
                ("point2", models.IntegerField()),
                ("point3", models.IntegerField()),
                ("point4", models.IntegerField()),
                ("date", models.DateTimeField(verbose_name="date battled")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=200)),
                ("qqnumber", models.CharField(max_length=200)),
                ("rate", models.FloatField()),
                ("firstplacetime", models.IntegerField()),
                ("secondplacetime", models.IntegerField()),
                ("thirdplacetime", models.IntegerField()),
                ("forthplacetime", models.IntegerField()),
                ("alltime", models.IntegerField()),
                ("timebeforeupdan", models.IntegerField()),
                ("dan", models.IntegerField()),
            ],
        ),
    ]
