# Generated by Django 4.2.4 on 2023-08-31 07:30

from django.db import migrations, models
import mahjong.models


class Migration(migrations.Migration):

    dependencies = [
        ("mahjong", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="yakuman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date recorded")),
                ("qqnumber", models.CharField(max_length=200)),
                ("yakuman_type", models.CharField(max_length=200)),
                (
                    "yakuman_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=mahjong.models.modify_path
                    ),
                ),
            ],
        ),
    ]
