# Generated by Django 4.2.4 on 2023-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong', '0003_majsoulbattle_majsouluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='majsoulbattle',
            name='doranum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
