adapters:
  - http
  - ws
debug: false
enableVerify: true
verifyKey: StarBot
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings:
  ## 其中的 7827 为 StarBot 的默认连接端口，如需修改此处，请在启动 StarBot 时使用 config.set("MIRAI_PORT", 端口号) 同步修改
  http:
    host: localhost
    port: 7827
    cors: ["*"]
    unreadQueueMaxSize: 100

  ## 其中的 7827 为 StarBot 的默认连接端口，如需修改此处，请在启动 StarBot 时使用 config.set("MIRAI_PORT", 端口号) 同步修改
  ws:
    host: localhost
    port: 7827
    reservedSyncId: -1
