# Generated by Django 4.2.4 on 2023-08-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Battle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User1", models.CharField(max_length=200)),
                ("User2", models.CharField(max_length=200)),
                ("User3", models.CharField(max_length=200)),
                ("User4", models.CharField(max_length=200)),
                ("points1", models.IntegerField()),
                ("points2", models.IntegerField()),
                ("points3", models.IntegerField()),
                ("points4", models.IntegerField()),
                ("data", models.DateTimeField(verbose_name="date battled")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Username", models.CharField(max_length=200)),
                ("qqnumber", models.CharField(max_length=200)),
            ],
        ),
    ]
